### ISSUE TITLE
Real time face tracking 

### ISSUE THREAD

**Issue by jayp84847** [keijiro/FaceLandmarkBarracuda#1]
Is it also working with real time face tracking?

**Comment by keijiro** [comment]
Sorry I can't understand what you meant exactly, but the face landmark detection model runs at 60 fps on my PC.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jayp84847** [comment]
Sorry for it. I want to use it for my real time face tracking project. I am working on face filter project so I want to know can I use it in real time face tracking. Or is there any module of this tracker so that I can use it in my project.

**Comment by keijiro** [comment]
https://github.com/keijiro/FaceMeshBarracuda

**Comment by jayp84847** [comment]
Thank you very much. For your support. I will try this.
