### ISSUE TITLE
Face texture 

### ISSUE THREAD

**Issue by jayp84847** [keijiro/FaceLandmarkBarracuda#2]

**Comment by keijiro** [comment]
Yes, I think so.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further technical issue related to this project.

**Comment by jayp84847** [comment]
Can you please help to do it. The code of this project is hard to crack for me so its hard to do it can you please help me to make code to create with it in unity3d material.  Please I really need help in it.

**Comment by keijiro** [comment]
What is your question? I can answer a question.

**Comment by jayp84847** [comment]
> ![facial-landmarks-summary](https://user-images.githubusercontent.com/81388248/136650235-9a79a959-5301-4343-888a-1e5d32561f6a.png)
> 
> Can we do this thing with this project. And after crop can we make material (with 2nd image) for face mesh module. ![1__5F3vd7z-FG_4Q5jES4yQQ](https://user-images.githubusercontent.com/81388248/136650277-e3680ddd-f49d-4fb9-aa1a-4a41b11225ee.png)

My question is can you create the code to make face material as I asked you with this project. I tried it but its hard to crack you barracuda code.

**Comment by keijiro** [comment]
> My question is can you create the code to make face material as I asked you with this project.

It's technically possible to create such an application using the Face Landmark model, but the main aim of this project is providing a thin wrapper library of MediaPipe Face Landmark. Creating an application is not in the scope of this project.

**Comment by jayp84847** [comment]
But can you help me with it's code plz.

**Comment by keijiro** [comment]
Please understand that this issue tracker is dedicated to track technical issues about this specific project. Please use other channels to solve problems about your own project.
