### ISSUE TITLE
Errors in WebGL

### ISSUE THREAD

**Issue by anysizesean** [keijiro/FaceLandmarkBarracuda#3]
Hey Keijiro - thanks so much for all these amazing repos! I tried building this one with the target set to WebGL, but I get errors in Chrome. Do you know if it is possible? Or does WebGL not work with compute shaders?

![FaceTrackWebGLError](https://user-images.githubusercontent.com/19315585/155032691-fc73ab9b-f7d4-40cf-97fe-b159effd991d.png)

**Comment by keijiro** [comment]
> Or does WebGL not work with compute shaders?

As far as I know, Unity WebGL player doesn't support GPU compute.

You may have to modify the package to run the model with the CPU worker.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
