### ISSUE TITLE
Access 3d coordinates of the predicted points

### ISSUE THREAD

**Issue by BaMarcy** [keijiro/FaceLandmarkBarracuda#5]
Hi Keijiro! Nicely well done, first of all!

Secondly, I would like to ask: how is it possible to get the 3d coordinates of the face mesh in runtime? Thanks!

**Comment by keijiro** [comment]
Please check the following thread: https://github.com/keijiro/FaceMeshBarracuda/issues/1

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by BaMarcy** [comment]
Thanks Keijiro! I will try!
